[feature]: Improve messaging in Keploy console #78
keploy/ui pull request #100
Opened 2022-10-25 03:06 UTC by valasubramanian-tw

# Pull Request Template

## Description

Added another condition to display 'Body is empty' is the request body length is 0 or empty.

Fixes #78 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality).

## How Has This Been Tested?

Since the frontend repo does not have any automated tests, I had verified this by testing the feature manually by running the frontend code and it works.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

2022-10-25 03:10 UTC, valasubramanian-tw commented
@nehagup Can you please review this PR and merge the changes if it is okay for you?

2022-10-25 14:45 UTC, nehagup requested changes
@valasubramanian-tw can you please sign the DCO?

2022-10-26 05:14 UTC, valasubramanian-tw commented
> @valasubramanian-tw can you please sign the DCO?

Done.

2022-10-27 14:49 UTC, valasubramanian-tw commented
@nehagup I have signed the DCO. Is there anything else pending to merge this PR?

2022-10-28 19:50 UTC, nehagup commented
Thanks @valasubramanian-tw I shall review this PR soon

2022-10-29 18:30 UTC, nehagup approved these changes

2022-10-29 18:41 UTC, merged

2022-10-30 15:02 UTC, valasubramanian-tw commented
@nehagup thanks for reviewing the PR. Can you please add