added preview and github pages action
keploy/ui pull request #50
Opened 2022-04-27 18:04 UTC by Ayush7614

This PR Contains

Adds a custom workflow to deploy docs using npm 
Adds an action to install, build and store the build as an artifact
Adds a workflow step to put up a GitHub comment on respective PRs after deploying

2022-04-27 18:17 UTC, Ayush7614 commented
cc @nehagup

2022-05-05 12:21 UTC, nehagup requested changes
Thanks for this @Ayush7614 👏

Is there any reference where we can see how will this work? How will be the experience?

2022-05-05 12:21 UTC, nehagup commented on .github/workflows/github-pages.yml
> +          node-version: '16'
We support node 14.x.x

2022-05-05 12:21 UTC, nehagup commented on .github/workflows/preview-build.yml
> +           node-version: '16'
Same as above

2022-05-05 12:21 UTC, nehagup commented on .github/workflows/preview-build.yml
> +          node-version: '16'
Same as above

2022-05-06 03:21 UTC, Ayush7614 commented
CC @nehagup 
This CI  is track web performance
And this is directly connected to lighthouserc.json to define the Lighthouse configuration.

![image](https://user-images.githubusercontent.com/67006255/167061653-7348c09a-3304-4ae7-9a61-e77f2a40be14.png)

2022-05-06 11:34 UTC, Ayush7614 commented
![IMG_20220506_170126](https://user-images.githubusercontent.com/67006255/167123811-ab71c1fa-9fa6-430b-a52f-2fe09b82658a.jpg)
This is working like this
Cc @nehagup

2022-05-06 13:29 UTC, nehagup approved these changes

2022-05-06 13:29 UTC, merged